### ISSUE TITLE
Table D sequence for reporting scatterometer data from CFOSAT

### ISSUE THREAD

**Issue by erget** [wmo-im/BUFR4#13] opened 2020-04-21 15:42 UTC
# Summary and purpose
New Table D sequence for the reporting of scatterometer data from CFOSAT

# Action proposed
The meeting is requested to review and approve the contents of this proposal for implementation within the second 2020 fast-track (FT2020-2) update to the WMO Manual on Codes.

# Discussions
Developed jointly by Centre national d'études spatiales (CNES) and the China National Space Administration (CNSA), the CFOSAT satellite carries two radar instruments: SWIM (Surface Waves Investigation and Monitoring), a wave scatterometer supplied by CNES for measurements of wave properties (direction, wavelength, etc.) and SCAT, a wind-field scatterometer supplied by CNSA for measurements of ocean surface wind vectors. The CFOSAT satellite was successfully launched on 29 October 2018 to a sun-synchronous orbit, with descending node crossing time at 07:00 and an altitude of 519 km.

The CFOSAT mission allows more accurate ocean forecasts and earlier warnings of severe weather events like storms and cyclones. CFOSAT also helps climatologists to learn more about air sea interactions which play a key role in climate.

The wave scaterometer, SCAT, is a Ku-Band (13.256 GHz), rotating fan beam scatterometer, with dual polarisation, HH and VV and a swath of 1000 km. For the rotating fan beam scatterometer there can be up to 18 sigma0 views per wind vector cell, as opposed to a maximum of 4 for pencil beam instruments. In order to standardize the BUFR encoding of these data, a new Table D sequence is proposed (3-12-034). The new sequence is essentially the same as the entry used for SeaWinds BUFR data (3-12-028) as far as the first parts containing general information, location/time information, wind information and brightness temperature information. The only difference is that in the last part the SeaWinds entry contains only 4 place holders for sigma0 views, whereas the CFOSAT entry contains 18 place holders.

# Detailed proposal
Add new entry 3-12-034 "CFOSAT scatterometer data" to BUFR Table D:
| Table references | Element name |
| --- | --- |
| 3-01-046 | Satellite   identifier, direction of motion, sensor, model function, software, resolution |
| 3-01-011 | Year,   month, day |
| 3-01-013 | Hour,   minute, second |
| 3-01-023 | Latitude/longitude   (coarse accuracy) |
| 0-08-025 | Time   difference qualifier |
| 2-01-136 | Change   data width |
| 0-04-006 | Second |
| 2-01-000 | Change   data width |
| 3-12-031 | Scatterometer   wind |
| 3-12-032 | Scatterometer   precipitation |
| 1-01-004 | Replicate   1 descriptor 4 times |
| 3-12-030 | Wind,   formal uncertainty, likelihood |
| 1-01-002 | Replicate   1 descriptor 2 times |
| 3-12-033 | Antenna   polarization, brightness temperature |
| 1-03-018 | Replicate   3 descriptor 18 times |
| 0-21-110 | Number   of inner-beam sigma-0 (forward of satellite) |
| 3-01-023 | Latitude/longitude   (coarse accuracy) |
| 3-21-028 | Radar   specification, normalized radar cross-section, Kp variance coefficient |

The meeting is requested to review and approve the contents of this proposal for implementation within the second 2020 fast-track (FT2020-2) update to the WMO Manual on Codes.

**Comment by efucile** [comment] 2020-04-28 13:31
duplicate of #12

**Closed by efucile** 2020-04-28 13:31 UTC
